### ISSUE TITLE
User Story: Bad search terms

### ISSUE THREAD

**Issue by atrieder** [theworkingmen/idb#109]
As a user, it would be helpful if the website let me know when something that I search for isn't acceptable (i.e., backslashes, percent symbols, etc. shouldn't cause the website to go blank).

**Comment by traylor1** [comment]
We've fixed this. Instead of accepting all characters and crashing for bad input, the backend now removes all non-alphanumeric characters (barring hyphens and whitespace). Also, blank searches are now acceptable and will return all instances.

Estimated time to completion = Actual time to completion = 30 minutes.

Future thought, this might break our highlighting code. If it does, we'll create a new issue.
