### ISSUE TITLE
User Story: Ensure Elements with Pictures

### ISSUE THREAD

**Issue by mitchellmarshe** [theworkingmen/idb#110]
As a user, I want to see that all elements have a picture in them if required.
![image](https://user-images.githubusercontent.com/31491237/38830678-be986a54-4182-11e8-9bfd-b815e78c41f1.png)

**Comment by traylor1** [comment]
![am_sign_lang_pic](https://user-images.githubusercontent.com/26069552/38833503-5684f64a-418b-11e8-8374-c8669dc9a348.png)
This isn't something we have too much control over. All of the images used are hosted on other sites and we just fetch them, however because of this they might not always load properly, thus the "no photo available" graphic. I hope this screenshot adequately indicates that we do have a photo for American Sign Language.

**Comment by abelhtt** [comment]
Although we agree that the default 'Image Not Found' does not look great. 
We've changed it to our favicon.ico image (which is a graduation cap).
![screen shot 2018-04-17 at 6 12 58 pm](https://user-images.githubusercontent.com/24883401/38903592-372c8f48-426b-11e8-8c5b-da659c89c7b6.png)

**Comment by abelhtt** [comment]
Assumption - The new image is better than the default 'No picture found' image. 
Estimated time - 30 minutes.
Actual time - 20 minutes.
